[package]
name = "client"
version = "0.1.0"
authors = ["Benjamin Saunders <ben.e.saunders@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
common = { path = "../common" }
tracing = "0.1.10"
tracing-subscriber = "0.1.6"
ash = "0.29"
lahar = { git = "https://github.com/Ralith/lahar", rev = "c27e8ebcd25fc712befc6e43b5576651da856cf0" }
winit = "0.20.0-alpha5"
ash-window = "0.1.0"
directories = "2.0.2"
vk-shader-macros = "0.2.2"
na = { package = "nalgebra", version = "0.19" }
