[package]
name = "server"
version = "0.1.0"
authors = ["Benjamin Saunders <ben.e.saunders@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
common = { path = "../common" }
tracing = "0.1.10"
tracing-subscriber = "0.1.6"
tokio = { version = "0.2", features = ["rt-threaded", "udp", "time", "macros"] }
quinn = { git = "https://github.com/djc/quinn.git", rev = "621060442d1efce759c61b6905296a4c86e79afa", default-features = false }
serde = { version = "1.0.104", features = ["derive", "rc"] }
toml = "0.5.5"
anyhow = "1.0.26"
rcgen = { version = "0.7.0", default-features = false }
hostname = "0.3.0"
futures = "0.3.1"
