[package]
name = "server"
version = "0.1.0"
authors = ["Benjamin Saunders <ben.e.saunders@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
common = { path = "../common" }
tracing = "0.1.10"
tracing-subscriber = "0.2"
tokio = { version = "0.2", features = ["rt-threaded", "time", "macros", "stream", "sync"] }
quinn = { git = "https://github.com/djc/quinn.git", rev = "5f81b5cf317305093b048d2211317f296b46a0e8", default-features = false }
serde = { version = "1.0.104", features = ["derive", "rc"] }
toml = "0.5.5"
anyhow = "1.0.26"
rcgen = { version = "0.7.0", default-features = false }
hostname = "0.3.0"
futures = "0.3.1"
hecs = "0.2.7"
rand = { version = "0.7.2", features = [ "small_rng" ] }
fxhash = "0.2.1"
na = { package = "nalgebra", version = "0.19" }
slotmap = "0.4.0"
