[package]
name = "common"
version = "0.1.0"
authors = ["Benjamin Saunders <ben.e.saunders@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.2"
serde = { version = "1.0.104", features = ["derive"] }
na = { package = "nalgebra", version = "0.19", features = ["serde-serialize"] }
bincode = "1.2.1"
anyhow = "1.0.26"
quinn = { git = "https://github.com/djc/quinn.git", rev = "5f81b5cf317305093b048d2211317f296b46a0e8", default-features = false }

[dev-dependencies]
approx = "0.3.2"
